logging:
  level:
    org:
      springframework:
        cloud: INFO
        integration: INFO
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
        bindings:
          routing-processor-in-0.consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          routing-processor-out-0.producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bindings:
        notification-producer-out-0.destination: notification_topic
        routing-processor-in-0.destination: notification_topic
        routing-processor-out-0.destination: event1_topic
        routing-processor-out-1.destination: event2_topic
        routing-processor-out-2.destination: event3_topic
        routing-processor-out-3.destination: notification_topic_dlq
        event1-in-0.destination: event1_topic
        event1-in-0.group: event1
        event2-in-0.destination: event2_topic
        event2-in-0.group: event2
        event3-in-0.destination: event3_topic
        event3-in-0.group: event3
    function:
      definition: notification-producer;routing-processor;event1;event2;event3