logging:
  level:
    org:
      springframework:
        cloud: INFO
        integration: INFO
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
        bindings:
          routing-processor-in-0.consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          routing-processor-out-0.producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bindings:
        notification-producer-out-0.destination: notification_topic
        routing-processor-in-0.destination: notification_topic
        routing-processor-out-0.destination: app1_topic
        routing-processor-out-1.destination: app2_topic
        routing-processor-out-2.destination: app3_topic
        routing-processor-out-3.destination: notification_topic_dlq
        app1-in-0.destination: app1_topic
        app1-in-0.group: app1
        app2-in-0.destination: app2_topic
        app2-in-0.group: app2
        app3-in-0.destination: app3_topic
        app3-in-0.group: app3
    function:
      definition: notification-producer;routing-processor;app1;app2;app3